# Generated by Django 4.1.2 on 2022-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('acronym', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=10)),
                ('overview', models.TextField()),
                ('founded', models.IntegerField()),
                ('totalstu', models.IntegerField()),
                ('interstu', models.IntegerField()),
                ('site', models.CharField(max_length=100)),
                ('acceptancerate', models.IntegerField()),
            ],
        ),
    ]
