# Generated by Django 4.1.2 on 2022-11-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='acceptancerate',
            new_name='acceptance_rate',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='interstu',
            new_name='international_students',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='totalstu',
            new_name='total_student',
        ),
        migrations.RemoveField(
            model_name='university',
            name='logo',
        ),
    ]
