# Generated by Django 4.1.2 on 2022-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, default='/imags/IMG_20170420_180049.jpg', null=True, upload_to='imags/'),
        ),
    ]
